before_build:
  - cd c:/projects/requestifytf2/src/
  - nuget restore
artifacts:
 # pushing a single file with environment variable in path and "Deployment name" specified
  - path: src\GUI\RequestifyTF2GUI\bin\Debug\RequestifyTF2GUI.exe
    name: forms
  - path: src\Plugins\RequestPlugin\bin\Debug\RequestPlugin.dll
    name: reqmusic
  - path: src\Plugins\TTSPlugin\bin\Debug\TTSPlugin.dll
    name: tts
  - path: src\Core\RequestifyTF2\bin\Debug\RequestifyTF2.dll
    name: core
  - path: src\Plugins\OofPlugin\bin\Debug\OofPlugin.dll
    name: oof
  - path: src\CLI\RequesifyCLI\bin\Debug\RequesifyCLI.exe
    name: cli


